
internal_variable_rename <- function(ds)
{
  ds <- dplyr::rename(ds
                      ,ProClinV1Id = proclinv1id
                      ,PatientId = patientid
                      ,TeamCode = teamcode
                      ,S1Age = v1_5
                      ,S1Sex = v1_6
                      ,S1Postcode = v1_7a
                      ,S1Ethnicity = v1_8
                      ,S1Diagnosis = v1_9
                      ,S1InHospitalStroke = v1_10
                      ,S1Onset = v1_11
                      ,S1OnsetMissing = v1_11a
                      ,S1OnsetDatePrecision = v1_11_1
                      ,S1OnsetTimePrecision = v1_11_2
                      ,S1ArrivedByAmbulance = v1_12
                      ,S1AmbulanceTrust = v1_12_1
                      ,S1FirstArrival = v1_13
                      ,S1FirstArrivalMissing = v1_13a
                      ,S1FirstWard = v1_14
                      ,S1ArrivalFirstStrokeUnit = v1_15
                      ,S1ArrivalFirstStrokeMissing = v1_15a
                      ,S1NotAdmittedStrokeUnit = v1_15b
                      ,S2HeartFailure = v2_1_1
                      ,S2Hypertension = v2_1_2
                      ,S2AtrialFibrillation = v2_1_3
                      ,S2Diabetes = v2_1_4
                      ,S2PrevStrokeTIA = v2_1_5
                      ,S2IfAFibAntiplatelet = v2_1_6
                      ,S2IfAFibAnticoagulant = v2_1_7
                      ,S2ModifiedRankinScore = v2_2
                      ,S2NIHSSArrival = v2_3
                      ,S2NIHSSArrivalLoC = v2_3_1
                      ,S2NIHSSArrivalLoCMissing = v2_3_1yn
                      ,S2NIHSSArrivalLoCQ = v2_3_2
                      ,S2NIHSSArrivalLoCQMissing = v2_3_2yn
                      ,S2NIHSSArrivalLoCC = v2_3_3
                      ,S2NIHSSArrivalLoCCMissing = v2_3_3yn
                      ,S2NIHSSArrivalBestGaze = v2_3_4
                      ,S2NIHSSArrivalBestGazeMissing = v2_3_4yn
                      ,S2NIHSSArrivalVisual = v2_3_5
                      ,S2NIHSSArrivalVisualMissing = v2_3_5yn
                      ,S2NIHSSArrivalFacialPalsy = v2_3_6
                      ,S2NIHSSArrivalFacialPalsyMissing = v2_3_6yn
                      ,S2NIHSSArrivalMotorArmLeft = v2_3_7
                      ,S2NIHSSArrivalMotorArmLeft = v2_3_7yn
                      ,S2NIHSSArrivalMotorArmRight = v2_3_8
                      ,S2NIHSSArrivalMotorArmRightMissing = v2_3_8yn
                      ,S2NIHSSArrivalMotorLegLeft = v2_3_9
                      ,S2NIHSSArrivalMotorLegLeftMissing = v2_3_9yn
                      ,S2NIHSSArrivalMotorLegRight = v2_3_10
                      ,S2NIHSSArrivalMotorLegRightMissing = v2_3_10yn
                      ,S2NIHSSArrivalLimbAtaxia = v2_3_11
                      ,S2NIHSSArrivalLimbAtaxiaMissing = v2_3_11yn
                      ,S2NIHSSArrivalSensory = v2_3_12
                      ,S2NIHSSArrivalSensoryMissing = v2_3_12yn
                      ,S2NIHSSArrivalBestLanguage = v2_3_13
                      ,S2NIHSSArrivalBestLanguageMissing = v2_3_13yn
                      ,S2NIHSSArrivalDysarthria = v2_3_14
                      ,S2NIHSSArrivalDysarthriaMissing = v2_3_14yn
                      ,S2NIHSSArrivalExtinction = v2_3_15
                      ,S2NIHSSArrivalExtinctionMissing = v2_3_15yn
                      ,S2BrainImagingDateTime = v2_4
                      ,S2BrainImagingDateTimeMissing = v2_4a
                      ,S2BrainImagingNotPerformed = v2_4b
                      ,S2StrokeType = v2_5
                      ,S2Thrombolysis = v2_6
                      ,S2ReasonNotThrombolysed = v2_6_1
                      ,S2NotThrombolysedHaemorrhagic = v2_6_2a
                      ,S2NotThrombolysedOutofWindow = v2_6_2b
                      ,S2NotThrombolysedComorbidity = v2_6_2c
                      ,S2NotThrombolysedMedication = v2_6_2d
                      ,S2NotThrombolysedRefused = v2_6_2e
                      ,S2NotThrombolysedDueAge = v2_6_2f
                      ,S2NotThrombolysedButImproving = v2_6_2g
                      ,S2NotThrombolysedDueSeverity = v2_6_2h
                      ,S2NotThrombolysedUnknownOnset = v2_6_2i
                      ,S2NotThrombolysedDueMedicalReason = v2_6_2j
                      ,S2TimeofThrombolysis = v2_7
                      ,S2TimeofThrombolysisMissing = v2_7a
                      ,S2ComplicationsofThrombolysis = v2_8
                      ,S2NumberofComplicationThrombolysis = number_complications
                      ,S2IntracranialHaemorrhageDueThrombolysis = v2_8_1a
                      ,S2AngioOedemaDueThrombolysis = v2_8_1b
                      ,S2ExtracranialHaemorrhageThrombolysis = v2_8_1c
                      ,S2OtherComplicationThrombolysis = v2_8_1d
                      ,S2NIHSS24Hrs = v2_9
                      ,S2NIHSS24HrsMissing = v2_9a
                      ,S2SwallowScreening4HrsDateTime = v2_10
                      ,S2SwallowScreening4HrsMissing = v2_10a
                      ,S2SwallowScreening4HrsNotDone = v2_10b
                      ,S2ReasonSwallosScreen4HrsNotDone = v2_10_1
                      ,S2TIAinLastMonth = v2_101
                      ,S2NeurovascularClinicAssessed = v2_102
                      ,S2BarthelPreStroke = v2_103
                      ,S2BrainImagingModality = v2_204
                      ,S2IntraArterialIntervention = v2_11
                      
                      
                      
                      
                      )
}