internal_afterApr15 <- function(x)
{
  ds <- dplyr::select(x,
                      proclinv1id	#		ProClinV1Id
                      ,patientid	#		PatientId
                      ,teamcode	#		TeamCode
                      ,initialdiagnosis	#		InitialDiagnosis
                      ,v1_5	#		S1AgeOnArrival
                      ,v1_6	#		S1Gender
                      ,v1_7a	#		S1PostcodeOut
                      ,v1_8	#		S1Ethnicity
                      ,v1_9	#		S1Diagnosis
                      ,v1_10	#		S1OnsetInHospital
                      ,v1_11	#		S1OnsetDateTime
                      ,v1_11a	#		S1OnsetTimeNotEntered
                      ,v1_11_1	#		S1OnsetDateType
                      ,v1_11_2	#		S1OnsetTimeType
                      ,v1_12	#		S1ArriveByAmbulance
                      ,v1_12_1	#		S1AmbulanceTrust
                      ,v1_13	#		S1FirstArrivalDateTime
                      ,v1_13a	#		S1FirstArrivalTimeNotEntered
                      ,v1_14	#		S1FirstWard
                      ,v1_15	#		S1FirstStrokeUnitArrivalDateTime
                      ,v1_15a	#		S1FirstStrokeUnitArrivalTimeNotEntered
                      ,v1_15b	#		S1FirstStrokeUnitArrivalNA
                      ,v2_1_1	#		S2CoMCongestiveHeartFailure
                      ,v2_1_2	#		S2CoMHypertension
                      ,v2_1_3	#		S2CoMAtrialFibrillation
                      ,v2_1_4	#		S2CoMDiabetes
                      ,v2_1_5	#		S2CoMStrokeTIA
                      ,v2_1_6	#		S2CoMAFAntiplatelet
                      ,v2_1_7	#		S2CoMAFAnticoagulent
                      ,v2_2	#		S2RankinBeforeStroke
                      ,v2_3	#		S2NihssArrival
                      ,v2_3_1	#		S2NihssArrivalLoc
                      ,v2_3_1yn	#		was v2_3_1 answered yes/no
                      ,v2_3_2	#		S2NihssArrivalLocQuestions
                      ,v2_3_2yn	#		was v2_3_2 answered yes/no
                      ,v2_3_3	#		S2NihssArrivalLocCommands
                      ,v2_3_3yn	#		was v2_3_3 answered yes/no
                      ,v2_3_4	#		S2NihssArrivalBestGaze
                      ,v2_3_4yn	#		was v2_3_4 answered yes/no
                      ,v2_3_5	#		S2NihssArrivalVisual
                      ,v2_3_5yn	#		was v2_3_5 answered yes/no
                      ,v2_3_6	#		S2NihssArrivalFacialPalsy
                      ,v2_3_6yn	#		was v2_3_6 answered yes/no
                      ,v2_3_7	#		S2NihssArrivalMotorArmLeft
                      ,v2_3_7yn	#		was v2_3_7 answered yes/no
                      ,v2_3_8	#		S2NihssArrivalMotorArmRight
                      ,v2_3_8yn	#		was v2_3_8 answered yes/no
                      ,v2_3_9	#		S2NihssArrivalMotorLegLeft
                      ,v2_3_9yn	#		was v2_3_9 answered yes/no
                      ,v2_3_10	#		S2NihssArrivalMotorLegRight
                      ,v2_3_10yn	#		was v2_3_10 answered yes/no
                      ,v2_3_11	#		S2NihssArrivalLimbAtaxia
                      ,v2_3_11yn	#		was v2_3_11 answered yes/no
                      ,v2_3_12	#		S2NihssArrivalSensory
                      ,v2_3_12yn	#		was v2_3_12 answered yes/no
                      ,v2_3_13	#		S2NihssArrivalBestLanguage
                      ,v2_3_13yn	#		was v2_3_13 answered yes/no
                      ,v2_3_14	#		S2NihssArrivalDysarthria
                      ,v2_3_14yn	#		was v2_3_14 answered yes/no
                      ,v2_3_15	#		S2NihssArrivalExtinctionInattention
                      ,v2_3_15yn	#		was v2_3_15 answered yes/no
                      ,v2_4	#		S2BrainImagingDateTime
                      ,v2_4a	#		S2BrainImagingTimeNotEntered
                      ,v2_4b	#		S2BrainImagingNotPerformed
                      ,v2_5	#		S2StrokeType
                      ,v2_6	#		S2Thrombolysis
                      ,v2_6_1	#		S2ThrombolysisNoReason
                      ,v2_6_2a	#		S2ThrombolysisNoButHaemorrhagic
                      ,v2_6_2b	#		S2ThrombolysisNoButTimeWindow
                      ,v2_6_2c	#		S2ThrombolysisNoButComorbidity
                      ,v2_6_2d	#		S2ThrombolysisNoButMedication
                      ,v2_6_2e	#		S2ThrombolysisNoButRefusal
                      ,v2_6_2f	#		S2ThrombolysisNoButAge
                      ,v2_6_2g	#		S2ThrombolysisNoButImproving
                      ,v2_6_2h	#		S2ThrombolysisNoButTooMildSevere
                      ,v2_6_2i	#		S2ThrombolysisNoButTimeUnknownWakeUp
                      ,v2_6_2j	#		S2ThrombolysisNoButOtherMedical
                      ,v2_7	#		S2ThrombolysisDateTime
                      ,v2_7a	#		S2ThrombolysisTimeNotEntered
                      ,v2_8	#		S2ThrombolysisComplications
                      ,number_complications	#		v2_8 total number of complications following thrombolysis
                      ,v2_8_1a	#		S2ThrombolysisComplicationSih
                      ,v2_8_1b	#		S2ThrombolysisComplicationAO
                      ,v2_8_1c	#		S2ThrombolysisComplicationEB
                      ,v2_8_1d	#		S2ThrombolysisComplicationOther
                      ,v2_8_2	#		S2ThrombolysisComplicationOtherDetails
                      ,v2_9	#		S2Nihss24Hrs
                      ,v2_9a	#		S2Nihss24HrsNK
                      ,v2_10	#		S2SwallowScreening4HrsDateTime
                      ,v2_10a	#		S2SwallowScreening4HrsTimeNotEntered
                      ,v2_10b	#		S2SwallowScreening4HrsNotPerformed
                      ,v2_10_1	#		S2SwallowScreening4HrsNotPerformedReason
                      ,v2_101	#		S2TIAInLastMonth
                      ,v2_102	#		S2NeurovascularClinicAssessed
                      ,v2_103	#		S2BarthelBeforeStroke
                      ,v2_104	#		S2BrainImagingModality
                      ,v2_11	#		S2IAI
                      ,v3_1	#		S3PalliativeCare
                      ,v3_1_1	#		S3PalliativeCareDecisionDate
                      ,v3_1_2	#		S3EndOfLifePathway
                      ,v3_2	#		S3StrokeNurseAssessedDateTime
                      ,v3_2a	#		S3StrokeNurseAssessedTimeNotEntered
                      ,v3_2b	#		S3StrokeNurseNotAssessed
                      ,v3_3	#		S3StrokeConsultantAssessedDateTime
                      ,v3_3a	#		S3StrokeConsultantAssessedTimeNotEntered
                      ,v3_3b	#		S3StrokeConsultantNotAssessed
                      ,v3_4	#		S3SwallowScreening72HrsDateTime
                      ,v3_4a	#		S3SwallowScreening72HrsTimeNotEntered
                      ,v3_4b	#		S3SwallowScreening72HrsNotPerformed
                      ,v3_4_1	#		S3SwallowScreening72HrsNotPerformedReason
                      ,v3_5	#		S3OccTherapist72HrsDateTime
                      ,v3_5a	#		S3OccTherapist72HrsTimeNotEntered
                      ,v3_5b	#		S3OccTherapist72HrsNotAssessed
                      ,v3_5_1	#		S3OccTherapist72HrsNotAssessedReason
                      ,OT_eligible_72h	#		OT_eligible_72h
                      ,v3_6	#		S3Physio72HrsDateTime
                      ,v3_6a	#		S3Physio72HrsTimeNotEntered
                      ,v3_6b	#		S3Physio72HrsNotAssessed
                      ,v3_6_1	#		S3Physio72HrsNotAssessedReason
                      ,PT_eligible_72h	#		PT_eligible_72h
                      ,v3_7	#		S3SpLangTherapistComm72HrsDateTime
                      ,v3_7a	#		S3SpLangTherapistComm72HrsTimeNotEntered
                      ,v3_7b	#		S3SpLangTherapistComm72HrsNotAssessed
                      ,v3_7_1	#		S3SpLangTherapistComm72HrsNotAssessedReason
                      ,SALTcomm_eligible_72h	#		SALTcomm_eligible_72h
                      ,v3_8	#		S3SpLangTherapistSwallow72HrsDateTime
                      ,v3_8a	#		S3SpLangTherapistSwallow72HrsTimeNotEntered
                      ,v3_8b	#		S3SpLangTherapistSwallow72HrsNotAssessed
                      ,v3_8_1	#		S3SpLangTherapistSwallow72HrsNotAssessedReason
                      ,SALTswallow_eligible_72h	#		SALTswallow_eligible_72h
                      ,v4_1	#		S4ArrivalDateTime
                      ,v4_1a	#		S4ArrivalTimeNotEntered
                      ,v4_2	#		S4FirstWard
                      ,v4_3	#		S4StrokeUnitArrivalDateTime
                      ,v4_3a	#		S4StrokeUnitArrivalTimeNotEntered
                      ,v4_3b	#		S4StrokeUnitArrivalNA
                      ,v4_4_pt	#		S4Physio
                      ,v4_4_1_end_pt	#		S4PhysioEndDate
                      ,v4_5_pt	#		S4PhysioDays
                      ,v4_6_pt	#		S4PhysioMinutes
                      ,v4_4_ot	#		S4OccTher
                      ,v4_4_1_end_ot	#		S4OccTherEndDate
                      ,v4_5_ot	#		S4OccTherDays
                      ,v4_6_ot	#		S4OccTherMinutes
                      ,v4_4_salt	#		S4SpeechLang
                      ,v4_4_1_end_salt	#		S4SpeechLangEndDate
                      ,v4_5_salt	#		S4SpeechLangDays
                      ,v4_6_salt	#		S4SpeechLangMinutes
                      ,v4_4_psy	#		S4Psychology
                      ,v4_4_1_end_psy	#		S4PsychologyEndDate
                      ,v4_5_psy	#		S4PsychologyDays
                      ,v4_6_psy	#		S4PsychologyMinutes
                      ,v4_7	#		S4RehabGoalsDate
                      ,v4_7a	#		S4RehabGoalsNone
                      ,v4_7_1	#		S4RehabGoalsNoneReason
                      ,v5_1	#		S5LocWorst7Days
                      ,v5_2	#		S5UrinaryTractInfection7Days
                      ,v5_3	#		S5PneumoniaAntibiotics7Days
                      ,v6_1	#		S6OccTherapistByDischargeDateTime
                      ,v6_1a	#		S6OccTherapistByDischargeTimeNotEntered
                      ,v6_1b	#		S6OccTherapistByDischargeNotAssessed
                      ,v6_1_1	#		S6OccTherapistByDischargeNotAssessedReason
                      ,v6_2	#		S6PhysioByDischargeDateTime
                      ,v6_2a	#		S6PhysioByDischargeTimeNotEntered
                      ,v6_2b	#		S6PhysioByDischargeNotAssessed
                      ,v6_2_1	#		S6PhysioByDischargeNotAssessedReason
                      ,v6_3	#		S6SpLangTherapistCommByDischargeDateTime
                      ,v6_3a	#		S6SpLangTherapistCommByDischargeTimeNotEntered
                      ,v6_3b	#		S6SpLangTherapistCommByDischargeNotAssessed
                      ,v6_3_1	#		S6SpLangTherapistCommByDischargeNotAssessedReason
                      ,v6_4	#		S6SpLangTherapistSwallowByDischargeDateTime
                      ,v6_4a	#		S6SpLangTherapistSwallowByDischargeTimeNotEntered
                      ,v6_4b	#		S6SpLangTherapistSwallowByDischargeNotAssessed
                      ,v6_4_1	#		S6SpLangTherapistSwallowByDischargeNotAssessedReason
                      ,v6_5	#		S6UrinaryContinencePlanDate
                      ,v6_5a	#		S6UrinaryContinencePlanNoPlan
                      ,v6_5_1	#		S6UrinaryContinencePlanNoPlanReason
                      ,v6_6	#		S6MalnutritionScreening
                      ,v6_6_1	#		S6MalnutritionScreeningDietitianDate
                      ,v6_6_1a	#		S6MalnutritionScreeningDietitianNotSeen
                      ,v6_7	#		S6MoodScreeningDate
                      ,v6_7a	#		S6MoodScreeningNoScreening
                      ,v6_7_1	#		S6MoodScreeningNoScreeningReason
                      ,v6_8	#		S6CognitionScreeningDate
                      ,v6_8a	#		S6CognitionScreeningNoScreening
                      ,v6_8_1	#		S6CognitionScreeningNoScreeningReason
                      ,v6_9	#		S6PalliativeCareByDischarge
                      ,v6_9_1	#		S6PalliativeCareByDischargeDate
                      ,v6_9_2	#		S6EndOfLifePathwayByDischarge
                      ,v6_10	#		S6FirstRehabGoalsDate
                      ,v6_11	#		S6IntPneumaticComp
                      ,v6_11_1	#		S6IntPneumaticCompStartDate
                      ,v6_11_2	#		S6IntPneumaticCompEndDate
                      ,v7_1	#		S7DischargeType
                      ,v7_1_1	#		S7DeathDate
                      ,v7_1_2	#		S7StrokeUnitDeath
                      ,v7_1_3	#		S7TransferTeamCode
                      ,v7_2	#		S7StrokeUnitDischargeDateTime
                      ,v7_2a	#		S7StrokeUnitDischargeTimeNotEntered
                      ,v7_3	#		S7HospitalDischargeDateTime
                      ,v7_3a	#		S7HospitalDischargeTimeNotEntered
                      ,v7_3_1	#		S7EndRehabDate
                      ,v7_4	#		S7RankinDischarge
                      ,v7_5	#		S7CareHomeDischarge
                      ,v7_5_1	#		S7CareHomeDischargeType
                      ,v7_6	#		S7HomeDischargeType
                      ,v7_7	#		S7DischargedEsdmt
                      ,v7_8	#		S7DischargedMcrt
                      ,v7_9	#		S7AdlHelp
                      ,v7_9_1	#		S7AdlHelpType
                      ,v7_9_2	#		S7DischargeVisitsPerWeek
                      ,v7_9_2a	#		S7DischargeVisitsPerWeekNK
                      ,v7_10	#		S7DischargeAtrialFibrillation
                      ,v7_10_1	#		S7DischargeAtrialFibrillationAnticoagulation
                      ,v7_11	#		S7DischargeJointCarePlanning
                      ,v7_12	#		S7DischargeNamedContact
                      ,v7_101	#		S7DischargeBarthel
                      ,v8_1	#		S8FollowUp
                      ,v8_1_1	#		S8FollowUpDate
                      ,v8_1_2	#		S8FollowUpType
                      ,v8_1_3	#		S8FollowUpBy
                      ,v8_1_4	#		S8FollowUpByOther
                      ,v8_2	#		S8MoodBehaviourCognitiveScreened
                      ,v8_2_1	#		S8MoodBehaviourCognitiveSupportNeeded
                      ,v8_2_2	#		S8MoodBehaviourCognitivePsychologicalSupport
                      ,v8_3	#		S8Living
                      ,v8_3_1	#		S8LivingOther
                      ,v8_4	#		S8Rankin6Month
                      ,v8_4_nk	#		S8Rankin6MonthNK
                      ,v8_5	#		S8PersistentAtrialFibrillation
                      ,v8_6_1	#		S8TakingAntiplateletDrug
                      ,v8_6_2	#		S8TakingAnticoagulent
                      ,v8_6_3	#		S8TakingLipidLowering
                      ,v8_6_4	#		S8TakingAntihypertensive
                      ,v8_7_1	#		S8SinceStrokeAnotherStroke
                      ,v8_7_2	#		S8SinceStrokeMyocardialInfarction
                      ,v8_7_3	#		S8SinceStrokeOtherHospitalisationIllness
                      ,country	#		Country
                      ,CHADS2_score	#		CHADS2_score
                      ,thromb_SSNAP_eligible	#		thromb_SSNAP_eligible
                      )
  return(ds)
}